// src/screens/AttendanceScreen.styles.ts

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
  },
  statusHero: {
    backgroundColor: "#011B51",
    paddingTop: 64,
    paddingBottom: 32,
    paddingHorizontal: 24,
    borderBottomWidth: 4,
    borderBottomColor: "#FED702",
  },
  studentBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    marginBottom: 16,
  },
  studentBadgeText: {
    color: "#FED702",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#FFFFFF",
    textTransform: "uppercase",
  },
  accentBar: {
    width: 48,
    height: 4,
    backgroundColor: "#FED702",
    borderRadius: 2,
    marginTop: 12,
    marginBottom: 12,
  },
  tagline: {
    fontSize: 14,
    color: "#E2E8F0",
    fontWeight: "500",
  },
  contentContainer: {
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: "800",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 20,
  },
  timeCard: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  timeDetails: {
    marginLeft: 12,
  },
  timeLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  timeValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#011B51",
    marginTop: 2,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  pickerContainer: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    overflow: "hidden",
  },
  picker: {
    width: "100%",
    height: 50,
    color: "#1E293B",
  },
  pinInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 20,
    color: "#011B51",
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 8,
  },
  submitButton: {
    backgroundColor: "#011B51",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderBottomWidth: 4,
    borderBottomColor: "#A51A21",
  },
  submitButtonDisabled: {
    opacity: 0.6,
    borderBottomColor: "#011B51",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1,
  },
  revokeButton: {
    alignSelf: "center",
    marginTop: 32,
    marginBottom: 24,
  },
  revokeButtonText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textDecorationLine: "underline",
  },
});