// src/screens/AttendanceScreen.styles.ts

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
  },
  statusHero: {
    backgroundColor: "#011B51",
    paddingTop: 64,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomWidth: 4,
    borderBottomColor: "#FED702",
  },
  studentBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    marginBottom: 16,
  },
  studentBadgeText: {
    color: "#FED702",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#FFFFFF",
    textTransform: "uppercase",
  },
  accentBar: {
    width: 48,
    height: 4,
    backgroundColor: "#FED702",
    borderRadius: 2,
    marginTop: 12,
    marginBottom: 12,
  },
  tagline: {
    fontSize: 14,
    color: "#E2E8F0",
    fontWeight: "500",
  },
  tabSegmentContainer: {
    flexDirection: "row",
    marginTop: 20,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 12,
    padding: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  tabSegmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  tabSegmentActive: {
    backgroundColor: "#FFFFFF",
  },
  tabSegmentText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  tabSegmentTextActive: {
    color: "#011B51",
  },
  contentContainer: {
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: "800",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 20,
  },
  timeCard: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  timeDetails: {
    marginLeft: 12,
  },
  timeLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  timeValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#011B51",
    marginTop: 2,
  },
  readinessContainer: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  statusPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  pillSuccess: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  pillWarning: {
    backgroundColor: "#FFFBEB",
    borderColor: "#FDE68A",
  },
  pillError: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FCA5A5",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  pillText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  readinessNotice: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 20,
  },
  readinessNoticeText: {
    fontSize: 12,
    color: "#1E40AF",
    fontWeight: "600",
    textAlign: "center",
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  pickerContainer: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    overflow: "hidden",
  },
  picker: {
    width: "100%",
    height: 50,
    color: "#1E293B",
  },
  pinInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 20,
    color: "#011B51",
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 8,
  },
  submitButton: {
    backgroundColor: "#011B51",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderBottomWidth: 4,
    borderBottomColor: "#A51A21",
  },
  submitButtonDisabled: {
    opacity: 0.6,
    borderBottomColor: "#011B51",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1,
  },
  revokeButton: {
    alignSelf: "center",
    marginTop: 32,
    marginBottom: 24,
  },
  revokeButtonText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textDecorationLine: "underline",
  },
  historyHeader: {
    fontSize: 16,
    fontWeight: "800",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  historyCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  historyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  historyCourseText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#011B51",
  },
  badgeOnTime: {
    backgroundColor: "#D1FAE5",
    borderColor: "#A7F3D0",
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  badgeOnTimeText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#065F46",
    textTransform: "uppercase",
  },
  badgeLate: {
    backgroundColor: "#FEF3C7",
    borderColor: "#FDE68A",
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  badgeLateText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B45309",
    textTransform: "uppercase",
  },
  badgeOverride: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
    alignSelf: "flex-start",
  },
  badgeOverrideText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#1E40AF",
    textTransform: "uppercase",
  },
  historySubText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  historyDateText: {
    fontSize: 11,
    fontWeight: "500",
    color: "#94A3B8",
    marginTop: 6,
  },
  emptyStateBox: {
    padding: 32,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748B",
    textAlign: "center",
  },
});