import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
  },
  brandHero: {
    backgroundColor: "#011B51",
    paddingTop: 64,
    paddingBottom: 32,
    paddingHorizontal: 24,
    borderBottomWidth: 4,
    borderBottomColor: "#FED702",
  },
  heroTitle: {
    fontSize: 34,
    fontWeight: "900",
    color: "#FFFFFF",
    textTransform: "uppercase",
  },
  heroSubTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FED702",
    textTransform: "uppercase",
    marginTop: -4,
  },
  accentBar: {
    width: 48,
    height: 4,
    backgroundColor: "#FED702",
    borderRadius: 2,
    marginTop: 16,
    marginBottom: 12,
  },
  tagline: {
    fontSize: 14,
    color: "#E2E8F0",
    fontWeight: "500",
    lineHeight: 20,
  },
  formContainer: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 40,
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: "800",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  sectionSubHeading: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "500",
    marginBottom: 24,
  },
  profileBadge: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderWidth: 1,
    padding: 14,
    borderRadius: 10,
    marginBottom: 20,
  },
  profileBadgeTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#1E40AF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  profileBadgeText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#011B51",
  },
  googleButton: {
    backgroundColor: "#011B51",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderBottomWidth: 4,
    borderBottomColor: "#FED702",
    shadowColor: "#011B51",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  googleButtonDisabled: {
    opacity: 0.6,
  },
  googleButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: "#011B51",
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: "#1E293B",
    fontWeight: "500",
  },
  inputDisabled: {
    backgroundColor: "#F1F5F9",
    color: "#64748B",
    borderColor: "#CBD5E1",
  },
  submitButton: {
    backgroundColor: "#011B51",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderBottomWidth: 4,
    borderBottomColor: "#A51A21",
  },
  submitButtonDisabled: {
    opacity: 0.6,
    borderBottomColor: "#011B51",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1,
  },
  secondaryButton: {
    alignSelf: "center",
    marginTop: 20,
    paddingVertical: 8,
  },
  secondaryButtonText: {
    color: "#64748B",
    fontWeight: "600",
    fontSize: 13,
  },
  domainNotice: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
  },
  domainNoticeText: {
    fontSize: 12,
    color: "#991B1B",
    fontWeight: "600",
    textAlign: "center",
  },
});