import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
  },
  brandHero: {
    width: "100%",
    height: Dimensions.get("window").height * 0.32,
    justifyContent: "center",
  },
  heroOverlay: {
    flex: 1,
    backgroundColor: "rgba(1, 27, 81, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  heroLogo: {
    width: 64,
    height: 64,
    resizeMode: "contain",
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: -0.5,
  },
  heroSubTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FED702",
    textTransform: "uppercase",
    marginTop: 2,
    letterSpacing: 0.5,
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 32,
    paddingBottom: 40,
    backgroundColor: "#FFFFFF",
  },
  viewStack: {
    width: "100%",
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: "900",
    color: "#011B51",
    textTransform: "uppercase",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  yellowBar: {
    width: 40,
    height: 4,
    backgroundColor: "#FED702",
    borderRadius: 2,
    marginTop: 8,
    marginBottom: 6,
    alignSelf: "center",
  },
  sectionSubHeading: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "600",
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 32,
  },
  googleButtonContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginVertical: 12,
  },
  googleButton: {
    width: "80%",
    height: 48,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  googleButtonDisabled: {
    opacity: 0.6,
    backgroundColor: "#F1F5F9",
  },
  googleButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1E293B",
  },
  domainNoticeText: {
    fontSize: 11,
    color: "#94A3B8",
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 15,
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 24,
  },
  secondaryButton: {
    alignSelf: "center",
    paddingVertical: 8,
    marginBottom: 36,
  },
  secondaryButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748B",
    textDecorationLine: "underline",
    textTransform: "uppercase",
    letterSpacing: 0.25,
    textAlign: "center",
  },
  guidelinesContainer: {
    borderTopWidth: 1,
    borderColor: "#F1F5F9",
    paddingTop: 28,
    marginTop: 12,
  },
  guidelinesTitle: {
    fontSize: 10,
    fontWeight: "900",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 14,
  },
  guidelineItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  guidelineNumber: {
    fontSize: 12,
    fontWeight: "900",
    color: "#011B51",
    marginRight: 10,
    width: 20,
  },
  guidelineText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: "#94A3B8",
    lineHeight: 17,
  },
  profileBadge: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderWidth: 1,
    padding: 14,
    borderRadius: 12,
    marginBottom: 18,
  },
  profileBadgeTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: "#1E40AF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  profileBadgeText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#011B51",
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputRow: {
    flexDirection: "row",
    width: "100%",
  },
  label: {
    fontSize: 10,
    fontWeight: "900",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
    marginLeft: 2,
  },
  input: {
    width: "100%",
    height: 44,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    fontWeight: "600",
    color: "#1E293B",
  },
  inputDisabled: {
    backgroundColor: "#F1F5F9",
    color: "#94A3B8",
    borderColor: "#E2E8F0",
  },
  submitButton: {
    width: "100%",
    height: 46,
    backgroundColor: "#011B51",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 3,
    borderBottomColor: "#A51A21",
    marginTop: 14,
    shadowColor: "#011B51",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  submitButtonDisabled: {
    opacity: 0.6,
    borderBottomColor: "#011B51",
  },
  buttonText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
});